const express=require("express");const multer=require("multer");const fs=require("fs");const path=require("path");const crypto=require("crypto");const {GoogleGenerativeAI}=require("@google/generative-ai");const ffmpeg=require("ffmpeg-static");const ffprobe=require("ffprobe-static");const {execFile}=require("child_process");
const app=express();const PORT=process.env.PORT||10000;const ROOT=__dirname;const UP=path.join(ROOT,"uploads");const OUT=path.join(ROOT,"outputs");fs.mkdirSync(UP,{recursive:true});fs.mkdirSync(OUT,{recursive:true});
const upload=multer({dest:UP,limits:{fileSize:(Number(process.env.MAX_FILE_MB)||500)*1024*1024}});app.use(express.json({limit:"2mb"}));app.use(express.static(path.join(ROOT,"public")));
const run=(bin,args)=>new Promise((resolve,reject)=>{execFile(bin,args,{maxBuffer:20*1024*1024},(error,stdout,stderr)=>{if(error)return reject(new Error(stderr||error.message));resolve(stdout);});});
function key(req){return req.headers["x-gemini-api-key"]||process.env.GEMINI_API_KEY}
app.get("/api/health",(req,res)=>res.json({ok:true,app:"Lynn Movie Recap New",version:"1.0.0"}));
app.post("/api/transcribe",upload.single("video"),async(req,res)=>{if(!req.file)return res.status(400).json({error:"Video မရှိပါ"});try{const k=key(req);if(!k)throw Error("Gemini API Key ထည့်ပါ");const gen=new GoogleGenerativeAI(k);const model=gen.getGenerativeModel({model:"gemini-3.8-flash"});const data=fs.readFileSync(req.file.path).toString("base64");const r=await model.generateContent([{inlineData:{data,mimeType:req.file.mimetype}},{text:"Transcribe this video accurately. Return only the spoken dialogue in Burmese or the original language. No explanation."}]);fs.unlinkSync(req.file.path);res.json({text:r.response.text()})}catch(e){try{fs.unlinkSync(req.file.path)}catch{}res.status(500).json({error:e.message})}});
app.post("/api/recap",async(req,res)=>{try{const k=key(req);if(!k)throw Error("Gemini API Key ထည့်ပါ");const gen=new GoogleGenerativeAI(k);const model=gen.getGenerativeModel({model:"gemini-3.8-flash"});const r=await model.generateContent("Write a natural, casual Burmese movie recap from this transcript. Keep it exciting and concise for a short video. Return only the recap text.\n\n"+String(req.body.text||""));res.json({text:r.response.text()})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/render",upload.fields([{name:"video",maxCount:1}]),async(req,res)=>{let out;try{if(!req.files?.video?.[0])throw Error("Video မရှိပါ");const v=req.files.video[0].path;out=path.join(OUT,crypto.randomUUID()+".mp4");const ratio=req.body.ratio||"9:16";const crf=Math.max(24,Math.min(32,Number(req.body.crf)||28));let vf=ratio==="16:9"?"scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2":ratio==="1:1"?"scale=720:720:force_original_aspect_ratio=decrease,pad=720:720:(ow-iw)/2:(oh-ih)/2":"scale=720:1280:force_original_aspect_ratio=decrease,pad=720:1280:(ow-iw)/2:(oh-ih)/2";await run(ffmpeg,["-y","-i",v,"-vf",vf,"-c:v","libx264","-preset","veryfast","-crf",String(crf),"-c:a","aac","-b:a","96k","-movflags","+faststart",out]);try{fs.unlinkSync(v)}catch{}res.json({download:"/api/download/"+path.basename(out)})}catch(e){res.status(500).json({error:e.message});}});
app.get("/api/download/:file",(req,res)=>{const f=path.basename(req.params.file);const p=path.join(OUT,f);if(!fs.existsSync(p))return res.status(404).send("File not found");res.download(p,"lynn-recap.mp4",()=>{try{fs.unlinkSync(p)}catch{}})});
app.listen(PORT,()=>console.log("Lynn Movie Recap New running on "+PORT));